### ISSUE TITLE
Silent ignoring of egui

### ISSUE THREAD

**Issue by mo8it** [qu1x/bevy_trackball#8]
When the `bevy_egui` feature isn't enabled, the new version of `bevy_trackball` doesn't render any egui elements. I spent some time trying to debug this because I thought it is from egui or bevy after updating both. But then I remembered the `bevy_egui` feature and added it. That fixed it and now the viewport stealing works! (The viewport stealing didn't work in a previous version of `bevy_trackball` which is why I removed the feature)

It would be nice to at least warn about this. Either at runtime or at least in the documentation.

**Comment by n3vu0r** [comment]
No clue how I missed this issue, I must have messed up the notifications, sorry!

Yes, we should definitely warn about this, thanks for pointing it out.

**Comment by n3vu0r** [comment]
Done with the latest release.
